'use client';

import { useMemo, useSyncExternalStore } from 'react';
import { motion } from 'framer-motion';
import Link from 'next/link';
import {
  Code2,
  TerminalSquare,
  FileSpreadsheet,
  FileText,
  ArrowRight,
  Sparkles,
  Zap,
  CheckCircle2,
  Brain,
  Globe,
  Server,
  Network,
  Gauge,
  FlaskConical,
  Palette,
  ListChecks,
  type LucideIcon,
} from 'lucide-react';
import { ThemeToggle } from './components/ThemeToggle';
import SiteSearch from './components/SiteSearch';
import studyMeta from './lib/studyMeta.json';

const fadeIn = {
  hidden: { opacity: 0, y: 20 },
  visible: { opacity: 1, y: 0, transition: { duration: 0.6 } }
};

const staggerContainer = {
  hidden: { opacity: 0 },
  visible: {
    opacity: 1,
    transition: {
      staggerChildren: 0.1
    }
  }
};

type Guide = { slug: string; title: string; desc: string; icon: LucideIcon; color: string; bg: string };
type Group = { id: string; title: string; blurb: string; guides: Guide[] };

// generated by scripts/study build-index: counts per guide plus a hash of every question title (for progress)
const meta = studyMeta as Record<string, { cards: number; questions: number; sections: number; keys?: string[] }>;

// FNV-1a over the normalised title, same function as the index builder
const fnv = (s: string) => {
  let h = 0x811c9dc5;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 0x01000193) >>> 0;
  }
  return h.toString(36);
};

const GROUPS: Group[] = [
  {
    id: 'start',
    title: 'Start here',
    blurb: 'The three pages to open first, whatever the role.',
    guides: [
      { slug: 'interview-prep', title: 'Interview Prep Guide', desc: 'Everything in one place, starting with a timed 2-hour review: JavaScript, TypeScript, React, Next.js, Node.js, databases, system design, performance, testing and more.', icon: FileText, color: 'text-indigo-500 dark:text-indigo-400', bg: 'bg-indigo-100 dark:bg-indigo-400/10' },
      { slug: 'interview-cheatsheet', title: 'Interview Cheatsheet', desc: 'A last-two-hours plan and a one-line answer for every topic, with a 30-minute must-know pass.', icon: ListChecks, color: 'text-fuchsia-500 dark:text-fuchsia-400', bg: 'bg-fuchsia-100 dark:bg-fuchsia-400/10' },
      { slug: 'genai', title: 'GenAI Explained', desc: 'LLMs, embeddings, RAG, tool calling, MCP and agents, streaming to React, and a full worked example of an AI quote-comparison flow.', icon: Brain, color: 'text-teal-500 dark:text-teal-400', bg: 'bg-teal-100 dark:bg-teal-400/10' },
    ],
  },
  {
    id: 'frontend',
    title: 'Frontend & web',
    blurb: 'Deep dives by topic. Each guide has categories, flashcards and a Quick Reference.',
    guides: [
      { slug: 'javascript', title: 'JavaScript', desc: 'Closures, prototypes and this, promises and the event loop, generators, modules, DOM events, TypeScript and CSS basics.', icon: Code2, color: 'text-amber-500 dark:text-amber-400', bg: 'bg-amber-100 dark:bg-amber-400/10' },
      { slug: 'react-training', title: 'React.js', desc: 'Hooks and effects, rendering performance, state, React 19 and Suspense, Router and forms, React Testing Library. Interactive labs are linked below.', icon: Code2, color: 'text-cyan-500 dark:text-cyan-400', bg: 'bg-cyan-100 dark:bg-cyan-400/10' },
      { slug: 'reactjs', title: 'React + TypeScript', desc: 'The same territory with a typing focus: typed components and hooks, generics, HOCs, state libraries, plus a one-page Quick Reference.', icon: Code2, color: 'text-blue-500 dark:text-blue-400', bg: 'bg-blue-100 dark:bg-blue-400/10' },
      { slug: 'nextjs', title: 'Next.js 16', desc: 'App Router, Server Components, Cache Components, proxy.ts, Server Actions and deployment, with diagrams.', icon: Code2, color: 'text-slate-500 dark:text-slate-300', bg: 'bg-slate-100 dark:bg-slate-400/10' },
      { slug: 'tailwind-css', title: 'CSS & Tailwind v4', desc: 'Box model, Flexbox and Grid, stacking contexts, responsive design, and Tailwind v4 (@theme, @source, container queries).', icon: Palette, color: 'text-sky-500 dark:text-sky-400', bg: 'bg-sky-100 dark:bg-sky-400/10' },
      { slug: 'web-platform', title: 'Web Platform & Tooling', desc: 'CORS, CSP and cookies, HTTP/2 and HTTP/3, caching, service workers, Docker, CI/CD, feature flags, Git and i18n.', icon: Globe, color: 'text-emerald-500 dark:text-emerald-400', bg: 'bg-emerald-100 dark:bg-emerald-400/10' },
    ],
  },
  {
    id: 'backend',
    title: 'Backend, design & performance',
    blurb: 'Server-side depth and the senior-level design conversation.',
    guides: [
      { slug: 'nodejs', title: 'Node.js', desc: 'Event loop, streams, workers, security, scaling, database patterns, testing with node:test and modules.', icon: TerminalSquare, color: 'text-green-500 dark:text-green-400', bg: 'bg-green-100 dark:bg-green-400/10' },
      { slug: 'system-design', title: 'System Design', desc: 'Architectural styles, microservices, messaging, sagas, real outages and AWS building blocks.', icon: Network, color: 'text-cyan-500 dark:text-cyan-400', bg: 'bg-cyan-100 dark:bg-cyan-400/10' },
      { slug: 'system-design-scale', title: 'System Design at Scale', desc: 'A senior-level answer to “design a full-stack app for millions of users”, end to end.', icon: Server, color: 'text-violet-500 dark:text-violet-400', bg: 'bg-violet-100 dark:bg-violet-400/10' },
      { slug: 'performance-optimization', title: 'Optimize at Every Layer', desc: 'Client, edge, API, server, cache and database: the full performance playbook and the numbers to know.', icon: Gauge, color: 'text-amber-500 dark:text-amber-400', bg: 'bg-amber-100 dark:bg-amber-400/10' },
    ],
  },
  {
    id: 'practice',
    title: 'Practice',
    blurb: 'Write code, not just read answers.',
    guides: [
      { slug: 'coding-questions', title: 'Coding Practice', desc: 'Algorithm, data-structure and React coding exercises with approach, code and trade-offs.', icon: TerminalSquare, color: 'text-rose-500 dark:text-rose-400', bg: 'bg-rose-100 dark:bg-rose-400/10' },
    ],
  },
];

const ALL_GUIDES = GROUPS.flatMap((g) => g.guides);

const LABS = [
  { href: '/react-training/labs#interview', title: 'AI Mock Interviewer', desc: 'Answer React questions and get feedback. Part of the React labs, with reducer, memo, RTL, forms and React 19 simulators.' },
  { href: '/javascript/labs', title: 'JavaScript labs', desc: 'Promise method visualisers, promise chaining, custom errors, CSS positioning and selector demos.' },
  { href: '/coding-questions/labs', title: 'Coding labs', desc: 'Step-through algorithm modules, HackerRank-style problems and React coding tasks.' },
  { href: '/system-design/labs', title: 'System design labs', desc: 'A sandbox, a load balancer and a chaos-monkey simulator for outages and resilience.' },
];

// The guides share one store of reviewed question titles in localStorage (same origin as this page).
// Read it without an effect and count, per guide, how many of its questions are in it.
function readProgress(): string {
  const next: Record<string, number> = {};
  try {
    const done = JSON.parse(localStorage.getItem('study-reviewed-titles-v1') || '{}') as Record<string, unknown>;
    const hashes = new Set(Object.keys(done).map(fnv));
    for (const g of ALL_GUIDES) {
      const n = (meta[g.slug]?.keys ?? []).filter((k) => hashes.has(k)).length;
      if (n) next[g.slug] = n;
    }
  } catch {
    /* storage unavailable: show no progress */
  }
  return JSON.stringify(next);
}
const subscribeProgress = (notify: () => void) => {
  window.addEventListener('storage', notify);
  return () => window.removeEventListener('storage', notify);
};
function useProgress(): Record<string, number> {
  const raw = useSyncExternalStore(subscribeProgress, readProgress, () => '{}');
  return useMemo(() => JSON.parse(raw) as Record<string, number>, [raw]);
}

// Cards marked "Again" in flashcards, anywhere, that haven't since been marked "Got it" —
// counted per guide the same way as progress (matching hashed question titles).
function readWeak(): string {
  const next: Record<string, number> = {};
  try {
    const weak = JSON.parse(localStorage.getItem('study-weak-titles-v1') || '{}') as Record<string, unknown>;
    const weakKeys = Object.keys(weak);
    next._total = weakKeys.length; // unique cards, regardless of how many guides each appears on
    const hashes = new Set(weakKeys.map(fnv));
    for (const g of ALL_GUIDES) {
      const n = (meta[g.slug]?.keys ?? []).filter((k) => hashes.has(k)).length;
      if (n) next[g.slug] = n;
    }
  } catch {
    /* storage unavailable: show no weak cards */
  }
  return JSON.stringify(next);
}
function useWeak(): Record<string, number> {
  const raw = useSyncExternalStore(subscribeProgress, readWeak, () => '{}');
  return useMemo(() => JSON.parse(raw) as Record<string, number>, [raw]);
}

function GuideCard({ guide, index, done }: { guide: Guide; index: number; done: number }) {
  const m = meta[guide.slug];
  const pct = m && done ? Math.max(1, Math.min(100, Math.round((done / m.questions) * 100))) : 0;
  return (
    <motion.div
      initial={{ opacity: 0, y: 30 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true }}
      transition={{ delay: (index % 3) * 0.08 }}
    >
      <Link href={`/${guide.slug}`} className="group flex h-full flex-col bg-white dark:bg-white/5 hover:bg-slate-50 dark:hover:bg-white/[0.07] border border-slate-200 dark:border-white/10 hover:border-indigo-300 dark:hover:border-white/20 rounded-3xl p-7 transition-all hover:-translate-y-1 shadow-sm dark:shadow-none">
        <div className={`w-12 h-12 rounded-2xl ${guide.bg} flex items-center justify-center mb-5`}>
          <guide.icon className={`w-6 h-6 ${guide.color}`} />
        </div>
        <h3 className="text-xl font-bold text-slate-900 dark:text-white mb-2 group-hover:text-indigo-600 dark:group-hover:text-indigo-300 transition-colors">{guide.title}</h3>
        <p className="text-slate-600 dark:text-slate-400 text-sm leading-relaxed flex-1">{guide.desc}</p>
        {m && (
          <div className="mt-5">
            <div className="flex items-center justify-between text-xs font-medium text-slate-500 dark:text-slate-400">
              <span>{m.questions} {guide.slug === 'interview-cheatsheet' ? 'one-line answers' : 'questions'}</span>
              {pct > 0 && <span className="text-indigo-600 dark:text-indigo-300">{pct}% reviewed</span>}
            </div>
            {pct > 0 && (
              <div className="mt-2 h-1.5 rounded-full bg-slate-200 dark:bg-white/10 overflow-hidden" role="progressbar" aria-valuenow={pct} aria-valuemin={0} aria-valuemax={100} aria-label={`${guide.title} reviewed`}>
                <div className="h-full rounded-full bg-indigo-500 dark:bg-indigo-400" style={{ width: `${pct}%` }} />
              </div>
            )}
          </div>
        )}
      </Link>
    </motion.div>
  );
}

export default function LandingPage() {
  const progress = useProgress();
  const weak = useWeak();
  const uniqueQuestions = meta._all?.questions ?? 0;

  const weakTotal = weak._total ?? 0;
  const weakGuide = Object.entries(weak).filter(([slug]) => slug !== '_total').sort((a, b) => b[1] - a[1])[0]?.[0];

  return (
    <div className="min-h-screen bg-slate-50 dark:bg-[#030712] selection:bg-indigo-500/30 text-slate-900 dark:text-slate-50 font-sans overflow-hidden transition-colors duration-300">

      {/* Dynamic Background */}
      <div className="fixed inset-0 z-0">
        <div className="absolute top-0 -left-1/4 w-1/2 h-1/2 bg-indigo-200/50 dark:bg-indigo-500/20 blur-[120px] rounded-full mix-blend-multiply dark:mix-blend-screen animate-pulse" style={{ animationDuration: '4s' }} />
        <div className="absolute bottom-0 -right-1/4 w-1/2 h-1/2 bg-violet-200/50 dark:bg-violet-600/20 blur-[120px] rounded-full mix-blend-multiply dark:mix-blend-screen animate-pulse" style={{ animationDuration: '6s', animationDelay: '1s' }} />
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-full h-full bg-[url('https://grainy-gradients.vercel.app/noise.svg')] opacity-40 dark:opacity-20 pointer-events-none mix-blend-overlay dark:mix-blend-soft-light" />
      </div>

      {/* Navigation */}
      <nav className="relative z-10 flex items-center justify-between px-6 py-6 max-w-7xl mx-auto">
        <div className="flex items-center gap-2">
          <div className="w-8 h-8 rounded-xl bg-gradient-to-br from-indigo-500 to-violet-600 flex items-center justify-center shadow-lg shadow-indigo-500/20">
            <Zap className="w-4 h-4 text-white" />
          </div>
          <span className="text-xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-slate-900 to-slate-600 dark:from-white dark:to-slate-400">
            DevSpar
          </span>
        </div>
        <div className="hidden md:flex items-center gap-8 text-sm font-medium text-slate-600 dark:text-slate-300">
          <Link href="#guides" className="hover:text-indigo-600 dark:hover:text-white transition-colors">Guides</Link>
          <Link href="#labs" className="hover:text-indigo-600 dark:hover:text-white transition-colors">Labs</Link>
          <Link href="#utilities" className="hover:text-indigo-600 dark:hover:text-white transition-colors">Utilities</Link>
        </div>
        <div className="flex items-center gap-4">
          <ThemeToggle />
          <Link
            href="/react-training/labs#interview"
            className="px-5 py-2 rounded-full bg-slate-200/50 hover:bg-slate-200 dark:bg-white/5 border border-slate-300/50 dark:border-white/10 dark:hover:bg-white/10 transition-colors text-sm font-medium backdrop-blur-md"
          >
            Mock Interview
          </Link>
        </div>
      </nav>

      <main className="relative z-10">
        {/* Hero Section */}
        <section className="pt-24 pb-28 px-6 max-w-7xl mx-auto flex flex-col lg:flex-row items-center gap-16">
          <motion.div
            className="flex-1 text-center lg:text-left"
            initial="hidden"
            animate="visible"
            variants={staggerContainer}
          >
            <motion.div variants={fadeIn} className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-indigo-100 dark:bg-indigo-500/10 border border-indigo-200 dark:border-indigo-500/20 text-indigo-700 dark:text-indigo-300 text-sm font-medium mb-6">
              <Sparkles className="w-4 h-4" />
              <span>Study guides, flashcards & an AI mock interviewer</span>
            </motion.div>

            <motion.h1 variants={fadeIn} className="text-5xl lg:text-7xl font-extrabold tracking-tight mb-8 leading-[1.1]">
              Master Engineering <br/>
              <span className="bg-clip-text text-transparent bg-gradient-to-r from-indigo-600 via-violet-600 to-fuchsia-600 dark:from-indigo-400 dark:via-violet-400 dark:to-fuchsia-400">
                Interviews Faster.
              </span>
            </motion.h1>

            <motion.p variants={fadeIn} className="text-lg text-slate-600 dark:text-slate-400 mb-10 max-w-2xl mx-auto lg:mx-0 leading-relaxed">
              {Math.floor(uniqueQuestions / 50) * 50}+ questions with diagrams, flashcards and progress tracking, from JavaScript and React to system design and GenAI. Free, and the utilities run entirely in your browser.
            </motion.p>

            <motion.div variants={fadeIn} className="flex flex-col sm:flex-row items-center gap-4 justify-center lg:justify-start">
              <Link
                href="/interview-prep"
                className="w-full sm:w-auto px-8 py-4 rounded-2xl bg-indigo-600 hover:bg-indigo-700 dark:bg-indigo-500 dark:hover:bg-indigo-600 text-white font-bold shadow-lg shadow-indigo-500/25 transition-all hover:-translate-y-1 flex items-center justify-center gap-2"
              >
                Start with the Prep Guide
                <ArrowRight className="w-5 h-5" />
              </Link>
              <Link
                href="#guides"
                className="w-full sm:w-auto px-8 py-4 rounded-2xl bg-white hover:bg-slate-50 dark:bg-white/5 dark:hover:bg-white/10 border border-slate-200 dark:border-white/10 text-slate-900 dark:text-white font-bold transition-all flex items-center justify-center shadow-sm dark:shadow-none"
              >
                Browse all guides
              </Link>
            </motion.div>

            <motion.div variants={fadeIn} className="mt-12 flex flex-wrap items-center justify-center lg:justify-start gap-x-6 gap-y-2 text-sm text-slate-500 dark:text-slate-400 font-medium">
              <div className="flex items-center gap-2"><CheckCircle2 className="w-4 h-4 text-emerald-500 dark:text-emerald-400"/> Flashcards & quizzes</div>
              <div className="flex items-center gap-2"><CheckCircle2 className="w-4 h-4 text-emerald-500 dark:text-emerald-400"/> Progress saved in your browser</div>
              <div className="flex items-center gap-2"><CheckCircle2 className="w-4 h-4 text-emerald-500 dark:text-emerald-400"/> Search across every guide</div>
            </motion.div>
          </motion.div>

          {/* Hero Visual */}
          <motion.div
            className="flex-1 w-full max-w-lg lg:max-w-none relative"
            initial={{ opacity: 0, scale: 0.9 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: 0.8, delay: 0.2 }}
          >
            <div className="relative rounded-3xl overflow-hidden border border-slate-200 dark:border-white/10 bg-white/50 dark:bg-slate-900/50 backdrop-blur-xl shadow-2xl shadow-indigo-500/10 p-2">
              <div className="absolute inset-0 bg-gradient-to-br from-indigo-500/5 via-transparent to-violet-500/5 pointer-events-none" />
              <div className="h-10 border-b border-slate-200 dark:border-white/10 flex items-center px-4 gap-2">
                <div className="w-3 h-3 rounded-full bg-red-500/80" />
                <div className="w-3 h-3 rounded-full bg-yellow-500/80" />
                <div className="w-3 h-3 rounded-full bg-green-500/80" />
              </div>
              <div className="p-6 space-y-4 relative">
                <div className="flex gap-4 items-start">
                  <div className="w-8 h-8 rounded-full bg-indigo-100 dark:bg-indigo-500/20 flex items-center justify-center shrink-0">
                    <Sparkles className="w-4 h-4 text-indigo-600 dark:text-indigo-400" />
                  </div>
                  <div className="bg-white dark:bg-white/5 rounded-2xl rounded-tl-none p-4 border border-slate-200 dark:border-white/10 shadow-sm dark:shadow-none">
                    <p className="text-sm text-slate-700 dark:text-slate-300">Explain the difference between useMemo and useCallback.</p>
                  </div>
                </div>
                <div className="flex gap-4 items-start flex-row-reverse">
                  <div className="w-8 h-8 rounded-full bg-emerald-100 dark:bg-emerald-500/20 flex items-center justify-center shrink-0">
                    <Code2 className="w-4 h-4 text-emerald-600 dark:text-emerald-400" />
                  </div>
                  <div className="bg-emerald-50 dark:bg-emerald-500/10 rounded-2xl rounded-tr-none p-4 border border-emerald-100 dark:border-emerald-500/20 shadow-sm dark:shadow-none">
                    <p className="text-sm text-emerald-800 dark:text-emerald-100">Both are for performance optimization, but useMemo memoizes a computed value, while useCallback memoizes the function definition itself to prevent unnecessary re-renders of child components.</p>
                  </div>
                </div>
              </div>
            </div>
          </motion.div>
        </section>

        {/* Guides */}
        <section id="guides" className="py-24 px-6 relative border-t border-slate-200 dark:border-white/5">
          <div className="max-w-7xl mx-auto">
            <motion.div
              initial="hidden"
              whileInView="visible"
              viewport={{ once: true, margin: "-100px" }}
              variants={staggerContainer}
              className="mb-12 text-center"
            >
              <h2 className="text-3xl md:text-5xl font-bold mb-6">Study <span className="text-indigo-600 dark:text-indigo-400">Guides</span></h2>
              <p className="text-slate-600 dark:text-slate-400 max-w-2xl mx-auto text-lg mb-8">Every guide has categories, one-line summaries, flashcards and progress tracking. A question you review in one guide counts as reviewed in all of them.</p>
              <SiteSearch />
              {weakTotal > 0 && weakGuide && (
                <Link
                  href={`/${weakGuide}#weak`}
                  className="mt-6 inline-flex items-center gap-2 rounded-full bg-amber-100 dark:bg-amber-400/10 border border-amber-200 dark:border-amber-500/20 text-amber-800 dark:text-amber-300 text-sm font-medium px-4 py-2 hover:bg-amber-200/70 dark:hover:bg-amber-400/20 transition-colors"
                >
                  ↻ {weakTotal} card{weakTotal === 1 ? '' : 's'} marked &ldquo;Again&rdquo; — review them now
                  <ArrowRight className="w-4 h-4" />
                </Link>
              )}
            </motion.div>

            <div className="space-y-16">
              {GROUPS.map((group) => (
                <div key={group.id}>
                  <div className="mb-6 flex flex-col sm:flex-row sm:items-end sm:justify-between gap-1">
                    <h3 className="text-2xl font-bold">{group.title}</h3>
                    <p className="text-sm text-slate-500 dark:text-slate-400">{group.blurb}</p>
                  </div>
                  <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
                    {group.guides.map((guide, i) => (
                      <GuideCard key={guide.slug} guide={guide} index={i} done={progress[guide.slug] ?? 0} />
                    ))}
                  </div>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Interactive labs */}
        <section id="labs" className="py-24 px-6 relative border-t border-slate-200 dark:border-white/5 bg-slate-100/50 dark:bg-slate-950/50">
          <div className="max-w-7xl mx-auto">
            <motion.div
              initial="hidden"
              whileInView="visible"
              viewport={{ once: true, margin: "-100px" }}
              variants={staggerContainer}
              className="mb-12 text-center"
            >
              <h2 className="text-3xl md:text-5xl font-bold mb-6">Interactive <span className="text-fuchsia-600 dark:text-fuchsia-400">Labs</span></h2>
              <p className="text-slate-600 dark:text-slate-400 max-w-2xl mx-auto text-lg">Simulators and step-through demos that go with the guides, plus the AI mock interviewer.</p>
            </motion.div>
            <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
              {LABS.map((lab, i) => (
                <motion.div
                  key={lab.href}
                  initial={{ opacity: 0, y: 30 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: i * 0.08 }}
                >
                  <Link href={lab.href} className="group block h-full bg-white dark:bg-white/5 hover:bg-slate-50 dark:hover:bg-white/[0.07] border border-slate-200 dark:border-white/10 hover:border-fuchsia-300 dark:hover:border-white/20 rounded-3xl p-7 transition-all hover:-translate-y-1 shadow-sm dark:shadow-none">
                    <div className="flex items-start justify-between mb-5">
                      <div className="w-12 h-12 rounded-2xl bg-fuchsia-100 dark:bg-fuchsia-400/10 flex items-center justify-center">
                        <FlaskConical className="w-6 h-6 text-fuchsia-500 dark:text-fuchsia-400" />
                      </div>
                      <ArrowRight className="w-5 h-5 text-slate-400 dark:text-slate-600 group-hover:text-fuchsia-600 dark:group-hover:text-white transition-all group-hover:translate-x-1" />
                    </div>
                    <h3 className="text-lg font-bold text-slate-900 dark:text-white mb-2">{lab.title}</h3>
                    <p className="text-slate-600 dark:text-slate-400 text-sm leading-relaxed">{lab.desc}</p>
                  </Link>
                </motion.div>
              ))}
            </div>
          </div>
        </section>

        {/* Utilities Section */}
        <section id="utilities" className="py-24 px-6 relative border-t border-slate-200 dark:border-white/5">
          <div className="max-w-7xl mx-auto">
            <motion.div
              initial="hidden"
              whileInView="visible"
              viewport={{ once: true, margin: "-100px" }}
              variants={staggerContainer}
              className="mb-16 text-center"
            >
              <h2 className="text-3xl md:text-5xl font-bold mb-6">Developer <span className="text-violet-600 dark:text-violet-400">Utilities</span></h2>
              <p className="text-slate-600 dark:text-slate-400 max-w-2xl mx-auto text-lg">Automate tedious tasks and manage your files securely right in your browser.</p>
            </motion.div>

            <div className="grid md:grid-cols-2 gap-6 max-w-4xl mx-auto">
              {[
                { title: 'CSV Merger Tool', desc: 'Upload, manage columns, and intelligently merge multiple CSV files securely in your browser.', icon: FileSpreadsheet, href: '/csv-tools', color: 'text-emerald-500 dark:text-emerald-400', bg: 'bg-emerald-100 dark:bg-emerald-400/10' },
                { title: 'PDF Suite', desc: 'Merge, compress, and manipulate PDF documents without sending your data to external servers.', icon: FileText, href: '/pdf-tools', color: 'text-rose-500 dark:text-rose-400', bg: 'bg-rose-100 dark:bg-rose-400/10' },
              ].map((item, i) => (
                <motion.div
                  key={item.title}
                  initial={{ opacity: 0, y: 30 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: i * 0.1 }}
                >
                  <Link href={item.href} className="group block h-full bg-white dark:bg-white/5 hover:bg-slate-50 dark:hover:bg-white/[0.07] border border-slate-200 dark:border-white/10 hover:border-violet-300 dark:hover:border-white/20 rounded-3xl p-8 transition-all hover:-translate-y-1 shadow-sm dark:shadow-none">
                    <div className="flex items-start justify-between mb-6">
                      <div className={`w-14 h-14 rounded-2xl ${item.bg} flex items-center justify-center`}>
                        <item.icon className={`w-7 h-7 ${item.color}`} />
                      </div>
                      <ArrowRight className="w-6 h-6 text-slate-400 dark:text-slate-600 group-hover:text-violet-600 dark:group-hover:text-white transition-colors group-hover:translate-x-1 duration-300" />
                    </div>
                    <h3 className="text-xl font-bold text-slate-900 dark:text-white mb-3 group-hover:text-violet-600 dark:group-hover:text-violet-300 transition-colors">{item.title}</h3>
                    <p className="text-slate-600 dark:text-slate-400 text-sm leading-relaxed">{item.desc}</p>
                  </Link>
                </motion.div>
              ))}
            </div>
          </div>
        </section>

        {/* Footer */}
        <footer className="border-t border-slate-200 dark:border-white/5 py-12 px-6 text-center text-slate-500 dark:text-slate-400 text-sm">
          <p>© {new Date().getFullYear()} DevSpar. Study guides and utilities that run in your browser.</p>
        </footer>
      </main>
    </div>
  );
}
